twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        App\Twig\: 'components/'
        App\Twig\Form\: 'components/Form/'
