# Dockerfile
FROM php:8.2-fpm

# Installer les dépendances système et PHP nécessaires
RUN apt-get update && apt-get install -y \
    libicu-dev \
    libzip-dev \
    libonig-dev \
    unzip \
    git \
    && docker-php-ext-install \
    intl \
    opcache \
    pdo_mysql \
    zip \
    && docker-php-ext-enable \
    intl opcache

# Installer Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Configurer le répertoire de travail
WORKDIR /var/www/symfony

# Copier les fichiers du projet Symfony
COPY . .

# Mettre à jour les permissions
RUN chown -R www-data:www-data /var/www/symfony

# Exposer le port utilisé par PHP-FPM
EXPOSE 9000
