services:

  database:
    image: mysql:8.0.33
    container_name: kopeck-db-local
    restart: unless-stopped
    ports:
      - '${DB_PORT}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - db-config:/etc/mysql

volumes:
  mysql_data:
  db-config:
