services:
  #  php-fpm:
  #    build:
  #      context: ..
  #      dockerfile: ../DockerFile
  #    volumes:
  #      - .:/var/www/symfony
  #    networks:
  #      - symfony-network
  #
  #  nginx:
  #    image: nginx:alpine
  #    volumes:
  #      - .:/var/www/symfony
  #      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #    ports:
  #      - "8080:80"
  #    networks:
  #      - symfony-network
  #      labels:
  #        - "traefik.enable=true"
  #        - "traefik.http.routers.appsymphony.rule=Host(`appsymfo.mondomaine.fr`)"
  #        - "traefik.http.services.appsymphony.loadbalancer.server.port=80"

  database:
    image: mysql:8.0
    container_name: kopeck-db-local
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - db-config:/etc/mysql

volumes:
  mysql_data:
  db-config:
