#version: '3'
#
#services:
####> doctrine/doctrine-bundle ###
#  database:
#    ports:
#      - "5432"
####< doctrine/doctrine-bundle ###
#
####> symfony/mailer ###
#  mailpit:
#      image: axllent/mailpit
#      ports:
#        - "1025:1025"  # SMTP
#        - "8025:8025"  # Interface Web
#      restart: unless-stopped
####< symfony/mailer ###
